spring.datasource.url=jdbc:postgresql://localhost:5432/comicapp
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto= update

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.main.allow-bean-definition-overriding=true

MyApp.app.secret=MyApp
MyApp.expires.in=604800